### ISSUE TITLE
Feature Request   The ability to use the Cv1 HMD as a tracker while using the controllers for hands

### ISSUE THREAD

**Issue by kyleo1234** [mm0zct/Oculus_Touch_Steam_Link#1]
I am trying to track a quest 2 with the Cv1 hmd so that i can use the cv1 controlers with it as well as using 3 vive trackers for fbt while keeping the playspaces alined and only having to deal with 2 play spaces insted of 3 (Cv1 Quest2 Vive) by tracking the quest2 with the cv1 headset and not using the quest controlers

**Comment by mm0zct** [comment]
This was implemented a while ago, sorry I forgot to close the issue :-)

**Comment by mm0zct** [comment]
I think someone is using the cv1 hmd as a hip tracker, not a hmd tracker.
