### ISSUE TITLE
oculus vr object tracks perfectly, controllers does not even track gyro nor movement.

### ISSUE THREAD

**Issue by LogMeIn-Hamachi** [mm0zct/Oculus_Touch_Steam_Link#17]
i see controllers working fine inside headset, inside ovr_test.exe (cordinates changes when i move controllers) but for some reason inside steamvr left and right controller are completely froozen. Not even gyro movement is tracked. While the 3rd oculus vr objects tracks perfectly. No idea how to resolve this. i have checked that headset is awake and everything.

**Comment by mm0zct** [comment]
Can you try enabling the external tracking option in the ovr_test window?

**Comment by LogMeIn-Hamachi** [comment]
> 

That worked! thank you so much, have a great day and thanks for the work with this software!
