### ISSUE TITLE
SteamVR update broke it?

### ISSUE THREAD

**Issue by data-1NV4L1D** [mm0zct/Oculus_Touch_Steam_Link#26]
SteamVR updated and I'm pretty sure it broke the whole thing.  Whenever I run the exe and open SteamVR it fails, but it opens fine without me running the exe.

**Comment by LogMeIn-Hamachi** [comment]
Move Oculus and Oculus_legacy out of steamvr folder. It launches after that.

Workaround.

**Comment by jetblade** [comment]
> Move Oculus and Oculus_legacy out of steamvr folder. It launches after that.
> 
> Its under "Drivers" in steamvr folder
> 
> Workaround.

Any other work arounds? It does not work for me.

**Comment by mm0zct** [comment]
You'll see this should be fixed now with the latest release :)

**Comment by jetblade** [comment]
> You'll see this should be fixed now with the latest release :)

its still broken for me
