### ISSUE TITLE
After using ALVR and this, my quest 2 link is bricked and wont connect

### ISSUE THREAD

**Issue by grinkmong** [mm0zct/Oculus_Touch_Steam_Link#3]
Every time i start SteamVR, it shows a "Device error"
![image](https://user-images.githubusercontent.com/97268922/150427829-3d9c1e08-5f16-4da7-86f7-4cd9abb5c040.png)
This has happened consistently after disabling the drivers for ALVR and this, and even removing them from the steamvr folder.

**Comment by RiskiVR** [comment]
pretty sure this is for Rift CV1, and not the quest

**Comment by mm0zct** [comment]
If you've disabled this driver, then it's not this driver's fault. In fact if the ovr_test.exe is not running my driver  doesn't even do anything in steam vr. Good luck solving your issue though.
