### ISSUE TITLE
There seems to be a haptics problem with some software.

### ISSUE THREAD

**Issue by Indigo-blue-MB** [mm0zct/Oculus_Touch_Steam_Link#9]
I am using it with HP Reverb G2(V1) and there seems to be a problem with haptics in some games.
In HL2VRMod, both controllers vibrate as soon as the title screen appears, and it doesn't stop until I turn haptics off in controller binding, including during the SteamVR menu.
In Into The Radius VR, both controllers vibrate at the title screen, but then there seems to be no problem in the game scene.
In Fracked, only the right hand vibrates at the title screen and it goes away after the game starts, but once it dies, the right or both hands start vibrating and do not stop. The vibration stops during the SteamVR menu.
These strange vibrations do not occur when using the Reverb G2 controller.
I am using machine translation, so apologies if the text is strange.
My PC:
CPU:9700K  GPU:RTX2070Super  MEM:32GB
HMD:Reverb G2(V1) & Rift Touch Controller

**Comment by mm0zct** [comment]
I missed this issue on here, but good it reported on Reddit or discord and it got fixed a while ago, should be sorted :-)

These programs send a steam of haptic events at 0Hz rather than no events, and I was rounding up to minimum feelable value rather than discarding the events.
